<?php

namespace ModernPDO\Keys;

use ModernPDO\Escaper;

/**
 * Unique table key.
 */
class UniqueKey extends Key
{
    /**
     * UniqueKey constructor.
     *
     * @param string|string[] $fields string or string array of fields
     * @param string          $name   key name if it is empty will be used generated by db
     */
    public function __construct(
        private string|array $fields,
        private string $name = '',
    ) {
    }

    /**
     * Builds and returns fields string.
     *
     * @param string|string[] $fields string or string array of fields
     */
    private function buildFields(Escaper $escaper, string|array $fields): string
    {
        if (\is_string($fields)) {
            return $escaper->column($fields);
        }

        $query = '';

        foreach ($fields as $field) {
            $query .= $escaper->column($field) . ', ';
        }

        return mb_substr($query, 0, -2);
    }

    /**
     * Returns key query.
     */
    public function build(Escaper $escaper): string
    {
        $query = '';

        if ($this->name !== '') {
            $query .= 'CONSTRAINT ' . $escaper->column($this->name) . ' ';
        }

        $query .= 'UNIQUE (' . $this->buildFields($escaper, $this->fields) . ')';

        return $query;
    }
}
