version: '3.9'

services:
  php:
    image: php:${PHP_VERSION}
    container_name: php
    restart: on-failure
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USERNAME: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_CHARSET: ${MARIADB_CHARSET}
      XDEBUG_MODE: ${XDEBUG_MODE}
      XDEBUG_CONFIG: "client_host=${XDEBUG_HOST} client_port=${FORWARD_XDEBUG_PORT}"
      XDEBUG_TRIGGER: ${XDEBUG_TRIGGER}
    depends_on:
      - postgres
      - mariadb
    volumes:
      - ${APP_DIR}:/var/www
    networks:
      - modernpdo
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
    volumes:
       - postgres:/var/lib/postgres
    networks:
      - modernpdo
    healthcheck:
      test: ["CMD", "pg_isready", "-U${POSTGRES_USERNAME}", "-d${POSTGRES_PASSWORD}"]
      retries: 3
      timeout: 5s

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USERNAME}
    volumes:
      - mariadb:/var/lib/mariadb
    networks:
      - modernpdo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MARIADB_ROOT_PASSWORD}"]
      retries: 3
      timeout: 5s

volumes:
  postgres:
  mariadb:

networks:
  modernpdo:
    driver: bridge
