name: Bug Report
description: Create a bug report
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Description
      description: "Please provide a description and way to reproduce the problem."
    validations:
      required: true
  - type: input
    attributes:
      label: ModernPDO Version
      description: "The ModernPDO version used."
      placeholder: "3.0.0"
    validations:
      required: true
  - type: input
    attributes:
      label: DBMS
      description: "The DBMS name and version used, if needed."
      placeholder: "MariaDB v10.5"
    validations:
      required: false
  - type: input
    attributes:
      label: PHP Version
      description: "The php version used, if needed."
      placeholder: "8.1"
    validations:
      required: false
