#
# We know this is bullshit, but right now we think it does not matter.
#

name: Tests

on:
  push:
    branches:
      - 'release'
      - 'hotfix'

permissions:
  contents: read

jobs:
  php-stan:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    name: PHP-STAN ${{ matrix.php }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Get cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, libxml, mbstring
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Srart PHP STAN
        run: composer stan

  database-tests:
      name: Tests Database
      runs-on: ubuntu-22.04
      strategy:
          fail-fast: false
          matrix:
            php: [8.1]
      steps:
          - name: Code checkout
            uses: actions/checkout@v3

          - name: Copy .env
            run: cp .env.example .env

          - name: Start docker-compose
            uses: isbang/compose-action@v1.5.1
            with:
              compose-file: "./docker-compose.yaml"

          - name: Get cache directory
            id: composer-cache
            run: |
                echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

          - name: Cache
            uses: actions/cache@v3
            with:
              path: ${{ steps.composer-cache.outputs.dir }}
              key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
              restore-keys: |
                ${{ runner.os }}-composer-${{ matrix.php }}-

          - name: Install dependencies
            run: composer install --no-interaction --no-progress --prefer-dist

          - name: Exec unit tests
            run: sleep 20;docker compose exec php "composer" "tests"

  php-salm:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.1]

    name: PHP-PSalm ${{ matrix.php }}

    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Get cache directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Srart PHP PSalm
        run: composer salm